### PR TITLE
Fix memory leak

### PR DESCRIPTION
**Pull request by joshalbrecht**
Basically, the problem is as described here (backwards and create_graph=True can cause a memory leak): pytorch/pytorch#4661

I adapted the solution from: https://github.com/caogang/wgan-gp/blob/master/gan_cifar10.py#L116

This fixed the memory leak for me (otherwise the usage was increasing with each batch during training, and would frequently run out of memory).  

Happy to give more details if desired, and thanks for making this nice project! :)

### CODE REVIEW

**Comment by akanimax** [comment]
Hi @joshalbrecht, 

Thank you so much for the PR. I haven't noticed the leak yet. But reading the issue, it seems to be a legitimate problem. 
Also, Is the problem still persistent in the v1.0.0 of PyTorch?

In any case, could you also include another commit to the PR to fix the same for the CondWGAN_GP (just further down in the same file) in the similar manner? I'd be happy to merge. Thanks again!

cheers :beers:!
@akanimax

**Comment by ndahlquist** [comment]
Ah yes, I was seeing the same problem but did not know how to fix. Can confirm this occurs on PyTorch v1.0.0. Thank you @joshalbrecht !

**Comment by SaoYan** [comment]
@joshalbrecht @akanimax 
I also observed memory leak. This PR should work (I always compute gp this way myself). 
However, there is no need to use *Variable* (and it should not be used because *Variable* has been deprecated since PyTorch 0.4).

The following code makes more sense:
```
merged = epsilon * real_samps.detach() + ((1 - epsilon) * fake_samps.detach())
merged.requires_grad_(True)
op = self.dis(merged, height, alpha)
gradient = th.autograd.grad(outputs=op, inputs=merged,
    grad_outputs=th.ones(op.size()).to(fake_samps.device),
    create_graph=True, retain_graph=True, only_inputs=True)[0]
gradients = gradients.view(gradients.size(0), -1)
penalty = reg_lambda * gradients.norm(2, dim=1).sub(1.).pow(2.).mean()
```

**Comment by akanimax** [comment]
Hi @SaoYan,

thanks a lot for the info. I'll merge this PR and make the changes you suggested.

Best regards,
@akanimax

**Comment by akanimax** [comment]
@SaoYan,

Your suggested changes (related to deprecation of the `Variable`) have been added in this commit -> [e9e215c2f7ca0bbbded08d34c834c2a3f43bb8d0](https://github.com/akanimax/pro_gan_pytorch/commit/e9e215c2f7ca0bbbded08d34c834c2a3f43bb8d0).

cheers :beers:!
@akanimax

**Comment by joshalbrecht** [comment]
Thanks for the fixes all!

**Pull request merged**
